### ISSUE TITLE
No response after executing "th -i provider.lua"

### ISSUE THREAD

**Issue by amiltonwong** [szagoruyko/cifar.torch#1]
Hi, Sergey,

I had downloaded cifar.torch, but no response appears after executing "th -i provider.lua". Here is snapshot. https://goo.gl/OPpKsE
Some steps I had missed? Could you suggest?

THX~
Milton

**Comment by szagoruyko** [comment]
Hi,
follow the post, copy paste to the interpreter the following lines:

``` lua
provider = Provider()
provider:normalize()
torch.save('provider.t7',provider)
```

**Comment by amiltonwong** [comment]
Thanks~
It works now :)
