### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by jundengdeng** [szagoruyko/cifar.torch#16]
Hi,
First of all, thanks for sharing.
I learned a lot from the code. Right now, I'm turning my attention on multi-gpu training for neural nets. It is very expensive to run the imageNet multi-gpu code. Could you please add a feature, which would allow us to run the code on multiple GPUs? Thanks!

Best,

Jun

**Comment by szagoruyko** [comment]
Hi, check https://github.com/facebook/fb.resnet.torch it has multi-GPU training for CIFAR-10

**Comment by jundengdeng** [comment]
Hi, good to know! Thanks for the quick reply! :)
