### ISSUE TITLE
CPU/CUNN version of NIN is not supported

### ISSUE THREAD

**Issue by ljk628** [szagoruyko/cifar.torch#3]
Hi Sergey, 

The CPU or Cunn version of NIN seems not working. The native SpacialAveragePooling layer does not support ceil() method yet. Simply remove :ceil() will result in 7x7 instead of 8x8 for each plane after the first averaging pooling layer and thus making the after layers broken.

Is there any quick way to fix this without changing the network design?  Using SpatialAveragePooling(2,2,2,2) can made the code work but is different from the original network. I am running experiment to see its performance.

**Comment by szagoruyko** [comment]
Thanks for reporting, I am aware of this. Adding ceil mode to SpatialAveragePooling is on our list, meanwhile your fix should work fine.

**Comment by ljk628** [comment]
Thanks, Sergey! I see similar issues reported elsewhere.
