### ISSUE TITLE
module 'cunn' not found:No LuaRocks module found for cunn

### ISSUE THREAD

**Issue by streamhsa** [szagoruyko/cifar.torch#5]
Hi Szagoruyko,

I have AMD GPU: Tonga GL. followed all the steps in the Readme file. I am at the last step "CUDA_VISIBLE_DEVICES=0 th train.lua --model vgg_bn_drop -s logs/vgg"
And I am getting the below error if I run "th train.lua".. Please help.

th train.lua 
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.1/trepl/init.lua:363: module 'cunn' not found:No LuaRocks module found for cunn
    no field package.preload['cunn']
    no file '/root/.luarocks/share/lua/5.1/cunn.lua'
    no file '/root/.luarocks/share/lua/5.1/cunn/init.lua'
    no file '/root/torch/install/share/lua/5.1/cunn.lua'
    no file '/root/torch/install/share/lua/5.1/cunn/init.lua'
    no file './cunn.lua'
    no file '/root/torch/install/lib/lua/5.1/cunn.lua'
    no file '/root/torch/install/lib/lua/5.1/cunn/init.lua'
    no file '/root/.luarocks/lib/lua/5.1/cunn.so'
    no file '/root/torch/install/lib/lua/5.1/cunn.so'
    no file './cunn.so'
    no file '/root/torch/install/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'error'
    /root/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
    train.lua:3: in main chunk
    [C]: in function 'dofile'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: ?

\Thanks.

**Comment by szagoruyko** [comment]
Hi, do `git checkout opencl` and try again

**Comment by streamhsa** [comment]
Still No luck... :(. I am getting the same error

git checkout opencl
Already on 'opencl'
Your branch is up-to-date with 'origin/opencl'.
root@HY-IN-SC01-99:~/Desktop/cltorch7/cifar/cifar.torch# th train.lua 
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.1/trepl/init.lua:363: module 'clnn' not found:No LuaRocks module found for clnn
    no field package.preload['clnn']
    no file '/root/.luarocks/share/lua/5.1/clnn.lua'
    no file '/root/.luarocks/share/lua/5.1/clnn/init.lua'
    no file '/root/torch/install/share/lua/5.1/clnn.lua'
    no file '/root/torch/install/share/lua/5.1/clnn/init.lua'
    no file './clnn.lua'
    no file '/root/torch/install/lib/lua/5.1/clnn.lua'
    no file '/root/torch/install/lib/lua/5.1/clnn/init.lua'
    no file '/root/.luarocks/lib/lua/5.1/clnn.so'
    no file '/root/torch/install/lib/lua/5.1/clnn.so'
    no file './clnn.so'
    no file '/root/torch/install/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'error'
    /root/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
    train.lua:3: in main chunk
    [C]: in function 'dofile'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: ?

**Comment by szagoruyko** [comment]
the error is different, there is no clnn now. do `luarocks install clnn`

**Comment by streamhsa** [comment]
My bad!!!  Thanks Sergey... It helped

Thank you very much... I am closing the issue. :)

**Comment by XXNDPB** [comment]
> Hi,Szagoruyko,

When i do git checkout opencl, there is a mistake happened
error: pathspec 'opencl' did not match any file(s) known to git.
